import 'package:flutter/foundation.dart';
import 'package:flutter/widgets.dart';

final class MobileLocalizations {
  const MobileLocalizations(this.locale);

  final Locale locale;

  static const LocalizationsDelegate<MobileLocalizations> delegate =
      _MobileLocalizationsDelegate();

  static MobileLocalizations of(BuildContext context) =>
      Localizations.of<MobileLocalizations>(context, MobileLocalizations) ??
      const MobileLocalizations(Locale('en'));

  static const Map<String, Map<String, String>> _values = {
    'en': {
      'switchLanguage': '切换到中文',
      'bootstrapTitle': 'Local platform features are unavailable',
      'bootstrapBody':
          'PickLogic has not read any media or files. Retry or restart the app.',
      'retryBootstrap': 'Retry local setup',
      'permissionError':
          'The media permission check did not finish; no media or files were read.',
      'safSaved':
          'Read-only folder access was saved; no file was moved or modified.',
      'safDenied': 'Read-only folder access was not granted.',
      'filesTitle': 'File collections',
      'homeSearchHint': 'Search files, sources, or types…',
      'fileTypes': 'File types',
      'smartCollections': 'Smart collections',
      'appsSources': 'Apps & sources',
      'phoneStorage': 'Phone storage',
      'phoneStorageDetail': 'Browse a shared folder with Android SAF',
      'categoryHome': 'Categories',
      'organize': 'Organize',
      'refresh': 'Refresh',
      'settings': 'Settings',
      'language': 'Language',
      'safeModeTitle': 'Developer Safe Mode',
      'safeModeDetail': 'Real files and media remain read-only.',
      'testWorkspace': 'Test Workspace',
      'testWorkspaceDetail':
          'SAF-authorized copies with rename, move, Test-Trash, and undo',
      'images': 'Images',
      'audio': 'Audio',
      'videos': 'Videos',
      'apps': 'Apps',
      'archives': 'Archives',
      'recent': 'Recent',
      'duplicates': 'Duplicates',
      'largeFiles': 'Large files',
      'favorites': 'Favorites',
      'sourcesEmpty': 'No verified app/source collections are visible yet.',
      'sourceInferred': 'Inferred source',
      'sourceWechat': 'WeChat',
      'sourceBrowser': 'Browser / downloads',
      'sourceCamera': 'Camera',
      'sourceBluetooth': 'Bluetooth',
      'sourceTransfer': 'Transfer',
      'cameraAndScreenshots': 'Camera / screenshots',
      'allItems': 'All',
      'comingNext': 'Coming next',
      'itemCount': '{count} items',
      'filesDescription':
          'All MediaStore items are browsable by date; one metadata page is read at a time. Use read-only SAF access for other shared folders.',
      'recentMedia': 'Media',
      'documents': 'Documents',
      'downloads': 'Downloads',
      'chooseSafReadOnly': 'Choose accessible folder (SAF, read-only)',
      'lazyLoad': 'Content loads on demand after opening this page.',
      'collectionUnavailable':
          'This collection is not accessible. Choose a shared folder with SAF instead.',
      'emptyCollection': 'No accessible items in this collection.',
      'loadedProgress': 'Loaded {loaded} of {total}',
      'loadMore': 'Load more',
      'loadingMore': 'Loading more…',
      'allLoaded': 'All {total} items loaded',
      'loadMoreError': 'The next metadata page could not be loaded. Try again.',
      'screenshotsTitle': 'Screenshots',
      'screenshotPermissionDetail':
          'After permission, only MediaStore metadata and bounded thumbnails for visible items are read. OCR is not automatic.',
      'screenshotLazy': 'Screenshots load on demand after opening this page.',
      'screenshotError': 'The screenshot collection is unavailable.',
      'screenshotEmpty': 'No accessible screenshots.',
      'screenshotCount':
          'All {total} screenshots are browsable by date · loaded {visible}/{total}',
      'groupNote':
          'Consecutive groups use time and source clues; a clue is not proof of app ownership.',
      'allMonths': 'All months',
      'currentMonth': 'This month',
      'consecutiveOnly': 'Consecutive',
      'reviewPending': 'Delete review',
      'reviewSummary':
          'Local review: Keep {keep} · Later {later} · Delete review {delete}',
      'reviewSafety':
          'These are session-local markers. Delete review never deletes, moves, or renames media.',
      'monthProgress':
          'Month filters cover {loaded} loaded items. Keep scrolling or load more until {total} are loaded.',
      'single': 'Single',
      'consecutive': '{count} consecutive',
      'sourceClue': 'Source clue: {source}',
      'folderSource': 'Folder: {name}',
      'unknownSource': 'Unknown source',
      'localMarker': 'Local marker: {state} · OCR: not requested',
      'markerSaved':
          '{state} · saved only as a local review marker; the original file was not modified',
      'keep': 'Keep',
      'later': 'Later',
      'deleteReview': 'Delete review',
      'protected': 'Protected',
      'unreviewed': 'Unreviewed',
      'photosTitle': 'Photos',
      'allPhotos': 'All',
      'cameraPhotos': 'Camera',
      'savedPhotos': 'Saved images',
      'photosNoAccess': 'PickLogic does not read photos without permission.',
      'photosLazy': 'Photos load on demand after opening this page.',
      'photosDescription':
          'Browse all photos by date. Loaded metadata is searchable and more results appear as you scroll; thumbnails load only when visible.',
      'photosSearchHint': 'Search photo name or type',
      'photosError': 'The photo collection is unavailable.',
      'photosNoMatches': 'No matches among loaded photos.',
      'storageTitle': 'Storage Insight',
      'byType': 'By type',
      'bySource': 'By source',
      'byApp': 'By app',
      'otherUnexplained': 'Other / unexplained',
      'observedDirectly': 'Observed directly',
      'systemReported': 'System-reported',
      'inferred': 'Inferred',
      'inaccessible': 'Inaccessible',
      'storageLoading': 'Reading the aggregate storage summary…',
      'accessible': 'Accessible',
      'restricted': 'Restricted',
      'volumeUsed': 'Device data volume used (system aggregate)',
      'volumeDetail': '{used} / {total}; cannot be attributed to files or apps',
      'sharedMedia': 'Visible shared-media scope',
      'selectedVisualOnly': 'Only user-selected photos and videos',
      'authorizedCollections': 'Only authorized MediaStore collections',
      'notAuthorized': 'Not authorized',
      'downloadStorage': 'Downloads, installers, and archives',
      'mediaStoreSafOnly': 'Only MediaStore/SAF-visible items',
      'safRequired': 'Choose a folder with SAF',
      'metadataQueue': 'Background incremental metadata queue',
      'queuePersistent':
          'Indexed {items}; completed {done}; failed {failed}; SQLite checkpoint resumes; OCR is not scheduled',
      'queueSession':
          'Indexed {items}; completed {done}; current session only; OCR is not scheduled',
      'pauseIndex': 'Pause indexing',
      'resumeIndex': 'Resume indexing',
      'checkNew': 'Check new content',
      'privateData': 'Other apps’ private data',
      'platformRestriction': 'Platform restriction',
      'explicitLimits': 'Explicit limits',
      'limitPlatform':
          'Android does not let third-party apps inspect this area directly.',
      'limitAggregate':
          'System aggregates include data PickLogic cannot enumerate or attribute.',
      'limitPrivate':
          'Other apps’ private folders are not read or estimated, and no cleanup action is offered.',
      'limitBounded':
          'Only paged metadata is processed; thumbnails load on demand when visible.',
      'limitDownloads':
          'Downloads and documents are visible only through MediaStore or user-selected SAF folders.',
      'safStorageNote':
          'SAF can expose a user-selected shared folder. Any media operation still requires a separate preview and confirmation.',
      'permissionMissing': 'Media read permission has not been granted.',
      'permissionSafety':
          'The first screen remains usable; PickLogic never bypasses Android scoped storage.',
      'selectMedia': 'Choose media permissions',
      'selectFolder': 'Choose shared folder',
      'searchField': 'Search by name, type, or category',
      'searchMinimum':
          'Enter at least two characters; only local metadata is searched.',
      'indexUnavailable': 'The local index is unavailable.',
      'noSearchResults': 'No matching results.',
      'insightTitle': 'Insight',
      'insightSummary': 'Local metadata identifies this as a {type} item.',
      'verifiedFacts': 'Verified facts',
      'ruleInferenceSection': 'Rule inference',
      'assessment': 'Assessment',
      'limitationsTitle': 'Limitations',
      'type': 'Type',
      'risk': 'Risk',
      'reviewRisk': 'Review',
      'safeRisk': 'Safe',
      'protectedRisk': 'Protected',
      'unknownRisk': 'Unknown',
      'confidence': 'Confidence',
      'bytes': 'Bytes',
      'size': 'Size',
      'modified': 'Time',
      'captured': 'Captured',
      'source': 'Source',
      'location': 'Location / origin',
      'screenshotFlag': 'Screenshot',
      'duplicateState': 'Duplicate state',
      'notCalculated': 'Not calculated',
      'duplicateFingerprintAvailable':
          'SHA-256 is available; grouping decides whether a duplicate exists',
      'duplicateNotChecked': 'Not checked; no duplicate claim is made',
      'classificationBasis': 'Basis',
      'classificationBasisValue': 'Extension {extension}; MIME {mime}',
      'fileInsightLimitation':
          'No file body, OCR result, app runtime state, or hidden private data was inspected.',
      'unknownInsightLimitation':
          'Current metadata is insufficient to identify this item. Unknown does not mean junk or safe to delete.',
      'yes': 'Yes',
      'no': 'No',
      'metadataEvidence':
          'Evidence: local metadata only; no full-file analysis was requested.',
      'open': 'Open',
      'fullScreenPreview': 'Preview',
      'openWithOtherApp': 'Open with another app',
      'copyLocation': 'Copy location',
      'systemTrash': 'Move to system trash',
      'systemTrashConfirmDetail':
          'Android will show its own confirmation. PickLogic never bypasses it.',
      'systemTrashDone': 'Android moved the item to system trash.',
      'systemTrashCancelled':
          'The system trash request was cancelled or unavailable.',
      'cancel': 'Cancel',
      'continueAction': 'Continue',
      'locate': 'Locate',
      'reviewQueue': 'Review',
      'more': 'More',
      'favoriteLocal':
          'Saved as a local favorite marker; the file was not modified.',
      'reviewQueued':
          'Added to the local review queue; the file was not modified.',
      'locationCopied': 'Location copied',
      'opened': 'Sent to the system viewer',
      'noViewer': 'No compatible viewer is available',
      'categoryDocuments': 'Documents',
      'categorySpreadsheets': 'Spreadsheets',
      'categoryPresentations': 'Presentations',
      'categoryPdf': 'PDF',
      'categoryImages': 'Images',
      'categoryVideos': 'Videos',
      'categoryAudio': 'Audio',
      'categoryArchives': 'Archives',
      'categoryInstallers': 'Installers',
      'categoryCode': 'Code',
      'categoryAcademicPapers': 'Academic papers',
      'categoryScreenshots': 'Screenshots',
      'categoryDownloads': 'Downloads',
      'categoryDuplicates': 'Duplicates',
      'categoryLargeFiles': 'Large files',
      'categoryUnknown': 'Unknown',
      'sourceFileSystem': 'File system',
      'sourceMediaStore': 'MediaStore',
      'sourceStorageAccessFramework': 'Selected SAF folder',
      'sourceDownloads': 'Downloads',
      'sourceAppOwned': 'App-owned storage',
      'sourceSynthetic': 'Synthetic fixture',
      'sourceUnknownKind': 'Unknown',
    },
    'zh': {
      'switchLanguage': '切换到英文',
      'bootstrapTitle': '本地平台能力暂时不可用',
      'bootstrapBody': 'PickLogic 未读取任何媒体或文件。请重试；若仍失败，请重新启动应用。',
      'retryBootstrap': '重试本地初始化',
      'permissionError': '媒体权限检查未完成；PickLogic 未读取任何媒体或文件。',
      'safSaved': '目录只读授权已保存；未移动或修改任何文件。',
      'safDenied': '未获得目录只读授权。',
      'filesTitle': '文件集合',
      'homeSearchHint': '搜索文件、来源、类型……',
      'fileTypes': '文件类型',
      'smartCollections': '智能集合',
      'appsSources': '应用与来源',
      'phoneStorage': '手机存储',
      'phoneStorageDetail': '通过 Android SAF 浏览共享目录',
      'categoryHome': '分类',
      'organize': '整理',
      'refresh': '刷新',
      'settings': '设置',
      'language': '语言',
      'safeModeTitle': '开发者安全模式',
      'safeModeDetail': '真实文件与媒体保持只读。',
      'testWorkspace': '测试工作区',
      'testWorkspaceDetail': '通过 SAF 授权，只对测试副本提供重命名、移动、测试回收站和撤销',
      'images': '图片',
      'audio': '音频',
      'videos': '视频',
      'apps': '应用',
      'archives': '压缩包',
      'recent': '最近',
      'duplicates': '重复项',
      'largeFiles': '大文件',
      'favorites': '收藏',
      'sourcesEmpty': '尚未发现可验证的应用/来源集合。',
      'sourceInferred': '推测来源',
      'sourceWechat': '微信',
      'sourceBrowser': '浏览器 / 下载',
      'sourceCamera': '相机',
      'sourceBluetooth': '蓝牙',
      'sourceTransfer': '互传',
      'cameraAndScreenshots': '相机 / 截图',
      'allItems': '全部',
      'comingNext': '即将支持',
      'itemCount': '{count} 项',
      'filesDescription':
          '全部 MediaStore 项目均可按日期浏览；每次只读取一页元数据。其他共享目录使用 SAF 只读授权。',
      'recentMedia': '媒体',
      'documents': '文档',
      'downloads': '下载',
      'chooseSafReadOnly': '选择可访问目录（SAF，只读）',
      'lazyLoad': '进入页面后按需加载。',
      'collectionUnavailable': '此集合当前不可访问；可改用 SAF 选择共享目录。',
      'emptyCollection': '此集合没有可访问项目。',
      'loadedProgress': '已加载 {loaded} / {total}',
      'loadMore': '继续加载',
      'loadingMore': '正在加载下一页…',
      'allLoaded': '已加载全部 {total} 项',
      'loadMoreError': '下一页元数据加载失败，请重试。',
      'screenshotsTitle': '截图',
      'screenshotPermissionDetail': '授权后只读取 MediaStore 元数据与可见项的有界缩略图；不会自动 OCR。',
      'screenshotLazy': '进入截图页后按需加载。',
      'screenshotError': '当前无法读取截图集合。',
      'screenshotEmpty': '没有可访问截图。',
      'screenshotCount': '全部 {total} 张截图均可按日期浏览 · 已加载 {visible}/{total}',
      'groupNote': '按时间与来源线索连续分组；来源线索不是应用归属结论。',
      'allMonths': '全部月份',
      'currentMonth': '本月',
      'consecutiveOnly': '连续截图',
      'reviewPending': '待处理',
      'reviewSummary': '本地审查队列：保留 {keep} · 稍后 {later} · 删除审查 {delete}',
      'reviewSafety': '这些是当前会话的本地标记；删除审查不会删除、移动或重命名媒体。',
      'monthProgress': '月份筛选覆盖当前已加载的 {loaded} 项；继续滚动或加载，直至完成 {total} 项。',
      'single': '单张',
      'consecutive': '连续 {count} 张',
      'sourceClue': '来源线索：{source}',
      'folderSource': '文件夹：{name}',
      'unknownSource': '来源未知',
      'localMarker': '本地标记：{state} · OCR：未请求',
      'markerSaved': '{state} · 仅保存为本地审查标记，未修改原文件',
      'keep': '保留',
      'later': '稍后',
      'deleteReview': '删除审查',
      'protected': '已保护',
      'unreviewed': '尚未判断',
      'photosTitle': '照片',
      'allPhotos': '全部',
      'cameraPhotos': '相机',
      'savedPhotos': '保存图片',
      'photosNoAccess': '未授权时 PickLogic 不读取照片。',
      'photosLazy': '进入照片页后按需加载。',
      'photosDescription': '全部照片均可按日期浏览；已加载元数据可搜索，继续滚动会补充结果；缩略图只在可见时按需读取。',
      'photosSearchHint': '搜索照片名称或类型',
      'photosError': '当前无法读取照片集合。',
      'photosNoMatches': '已加载照片中没有匹配项。',
      'storageTitle': '存储知件',
      'byType': '按类型',
      'bySource': '按来源',
      'byApp': '按应用',
      'otherUnexplained': '其他 / 未解释',
      'observedDirectly': '直接观察',
      'systemReported': '系统报告',
      'inferred': '规则推断',
      'inaccessible': '不可访问',
      'storageLoading': '正在读取系统存储摘要…',
      'accessible': '可访问',
      'restricted': '受限',
      'volumeUsed': '设备数据卷已用空间（系统聚合）',
      'volumeDetail': '{used} / {total}；不可据此归因到文件或应用',
      'sharedMedia': '共享媒体可见范围',
      'selectedVisualOnly': '仅限用户选择的照片和视频',
      'authorizedCollections': '仅限已授权的 MediaStore 集合',
      'notAuthorized': '尚未授权，无法检查',
      'downloadStorage': '下载、安装包与压缩包',
      'mediaStoreSafOnly': '仅统计 MediaStore/SAF 可见项',
      'safRequired': '需要用户通过 SAF 选择目录',
      'metadataQueue': '后台增量元数据队列',
      'queuePersistent':
          '已索引 {items} 项；完成 {done} 批；失败 {failed} 批；SQLite 检查点可恢复；不调度 OCR',
      'queueSession': '已索引 {items} 项；完成 {done} 批；当前会话状态；不调度 OCR',
      'pauseIndex': '暂停索引',
      'resumeIndex': '继续索引',
      'checkNew': '检查新增内容',
      'privateData': '其他应用私有数据',
      'platformRestriction': '平台限制',
      'explicitLimits': '明确限制',
      'limitPlatform': '当前 Android 权限不允许第三方应用直接检查该部分。',
      'limitAggregate': '系统聚合值包含 PickLogic 无法枚举或归因的数据。',
      'limitPrivate': '不读取其他应用私有目录，不估算其内容，不提供清理按钮。',
      'limitBounded': '仅处理按页返回的元数据；缩略图在可见时按需读取。',
      'limitDownloads': '下载和文档仅在 MediaStore 或用户选择的 SAF 范围内可见。',
      'safStorageNote': '可使用 SAF 查看用户明确选择的共享目录；任何媒体操作仍需另行预览与确认。',
      'permissionMissing': '尚未获得媒体只读权限。',
      'permissionSafety': '首屏保持可用；不会在后台绕过 Android scoped storage。',
      'selectMedia': '选择媒体权限',
      'selectFolder': '选择共享目录',
      'searchField': '按名称、类型或分类搜索',
      'searchMinimum': '输入至少两个字符；仅搜索本地元数据。',
      'indexUnavailable': '当前索引不可访问。',
      'noSearchResults': '没有匹配结果。',
      'insightTitle': '知件',
      'insightSummary': '本地元数据将此项目识别为 {type}。',
      'verifiedFacts': '已验证事实',
      'ruleInferenceSection': '规则推断',
      'assessment': '判断',
      'limitationsTitle': '无法确认的部分',
      'type': '类型',
      'risk': '风险',
      'reviewRisk': '需审查',
      'safeRisk': '可安全处理',
      'protectedRisk': '受保护',
      'unknownRisk': '未知',
      'confidence': '置信度',
      'bytes': '字节',
      'size': '大小',
      'modified': '时间',
      'captured': '时间',
      'source': '来源',
      'location': '位置 / 来源',
      'screenshotFlag': '是否截图',
      'duplicateState': '重复状态',
      'notCalculated': '尚未计算',
      'duplicateFingerprintAvailable': '已有 SHA-256 指纹；是否重复仍以分组结果为准',
      'duplicateNotChecked': '尚未检查，不作重复结论',
      'classificationBasis': '依据',
      'classificationBasisValue': '扩展名 {extension}；MIME {mime}',
      'fileInsightLimitation': '未读取文件正文、OCR 结果、应用运行状态或受限私有数据。',
      'unknownInsightLimitation': '现有元数据不足以识别该项目；未知不等于垃圾，也不代表可以删除。',
      'yes': '是',
      'no': '否',
      'metadataEvidence': '证据：仅使用本地元数据；未请求整文件分析。',
      'open': '打开',
      'fullScreenPreview': '预览',
      'openWithOtherApp': '用其他应用打开',
      'copyLocation': '复制位置',
      'systemTrash': '移到系统回收站',
      'systemTrashConfirmDetail': 'Android 将再次显示系统确认；PickLogic 不会绕过该确认。',
      'systemTrashDone': 'Android 已将该项目移到系统回收站。',
      'systemTrashCancelled': '系统回收站操作已取消或不可用。',
      'cancel': '取消',
      'continueAction': '继续',
      'locate': '定位',
      'reviewQueue': '审查',
      'more': '更多',
      'favoriteLocal': '已加入本地收藏标记，未修改原文件。',
      'reviewQueued': '已加入本地审查队列，未修改原文件。',
      'locationCopied': '位置已复制',
      'opened': '已交给系统打开',
      'noViewer': '没有可用的打开方式',
      'categoryDocuments': '文档',
      'categorySpreadsheets': '表格',
      'categoryPresentations': '演示文稿',
      'categoryPdf': 'PDF',
      'categoryImages': '图片',
      'categoryVideos': '视频',
      'categoryAudio': '音频',
      'categoryArchives': '压缩包',
      'categoryInstallers': '安装包',
      'categoryCode': '代码',
      'categoryAcademicPapers': '学术论文',
      'categoryScreenshots': '截图',
      'categoryDownloads': '下载',
      'categoryDuplicates': '重复项',
      'categoryLargeFiles': '大文件',
      'categoryUnknown': '未知',
      'sourceFileSystem': '文件系统',
      'sourceMediaStore': 'MediaStore',
      'sourceStorageAccessFramework': '已选 SAF 目录',
      'sourceDownloads': '下载',
      'sourceAppOwned': '应用自有存储',
      'sourceSynthetic': '合成测试数据',
      'sourceUnknownKind': '未知',
    },
  };

  String text(String key) =>
      _values[locale.languageCode]?[key] ?? _values['en']![key] ?? key;

  String format(String key, Map<String, Object> values) {
    var result = text(key);
    for (final entry in values.entries) {
      result = result.replaceAll('{${entry.key}}', '${entry.value}');
    }
    return result;
  }
}

final class _MobileLocalizationsDelegate
    extends LocalizationsDelegate<MobileLocalizations> {
  const _MobileLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) =>
      locale.languageCode == 'en' || locale.languageCode == 'zh';

  @override
  Future<MobileLocalizations> load(Locale locale) =>
      SynchronousFuture(MobileLocalizations(locale));

  @override
  bool shouldReload(_MobileLocalizationsDelegate old) => false;
}
