name: picklogic_desktop
description: PickLogic Desktop and Pro.
version: 0.1.0-alpha+1
publish_to: none

environment:
  sdk: ^3.12.0

resolution: workspace

dependencies:
  archive: 4.0.9
  desktop_drop: 0.7.1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  pdfrx: 2.4.7
  picklogic_classification_rules:
    path: ../../packages/classification_rules
  picklogic_core_models:
    path: ../../packages/core_models
  picklogic_duplicate_engine:
    path: ../../packages/duplicate_engine
  picklogic_file_index:
    path: ../../packages/file_index
  picklogic_insight_engine:
    path: ../../packages/insight_engine
  picklogic_literature_core:
    path: ../../packages/literature_core
  picklogic_operation_planner:
    path: ../../packages/operation_planner
  picklogic_preview_core:
    path: ../../packages/preview_core
  picklogic_research_core:
    path: ../../packages/research_core
  picklogic_search_index:
    path: ../../packages/search_index
  picklogic_shared_ui:
    path: ../../packages/shared_ui
  picklogic_system_insight_core:
    path: ../../packages/system_insight_core
  picklogic_windows_bridge:
    path: ../../platform/windows_bridge
  video_player_win: 3.2.2

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
